# Alias Analysis Unit Tests

add_subdirectory(DemandDriven/DDA)
add_subdirectory(InclusionBased/AserPTA)
add_subdirectory(InclusionBased/FlowSensitive)
add_subdirectory(InclusionBased/LotusAA)
add_subdirectory(InclusionBased/SparrowAA)
add_subdirectory(InclusionBased/TPA)
add_subdirectory(UnificationBased/DyckAA)
add_subdirectory(UnificationBased/SeaDsa)
add_subdirectory(Specialized/AllocAA)
add_subdirectory(Specialized/DFPA)
if(LOTUS_ENABLE_TYPE_QUALIFIER)
  add_subdirectory(Specialized/TypeQualifier)
endif()
add_subdirectory(Specialized/UnderApproxAA)
add_subdirectory(Infrastructure/PtsSet)
