add_subdirectory(CFG)
add_subdirectory(ControlDependence)
add_subdirectory(NullPointer)
add_subdirectory(TypeHierarchy)
add_subdirectory(DebugInfo)
add_subdirectory(FeatureExtraction)
add_subdirectory(Loop)
add_subdirectory(Profile)
add_subdirectory(Purity)
add_subdirectory(SCCP)
add_subdirectory(Multiplicity)
add_subdirectory(ParameterSummary)
