set(Concurrency_SOURCES
  ConcurrencyFacade.cpp
  Utils/ThreadAPI.cpp
  Utils/ThreadFlowGraph.cpp
  Utils/BVClock.cpp
  Utils/FBVClock.cpp
  Utils/RAIILockTracker.cpp
  Utils/CppAtomics.cpp
  Utils/ThreadLocalAnalysis.cpp
  OpenMP/OpenMPSemantics.cpp
  OpenMP/OpenMPTaskGraph.cpp
  OpenMP/DataSharingAnalysis.cpp
  MHP/MHPAnalysis.cpp
  MHP/StaticVectorClockMHP.cpp
  MHP/HappensBeforeAnalysis.cpp
  LockSet/LockSetAnalysis.cpp
  Memory/EscapeAnalysis.cpp
  Memory/StaticThreadSharingAnalysis.cpp
  JoinTarget/JoinTargetAnalysis.cpp
  MPI/MPIAnalysis.cpp
  MPI/MPIAbstractState.cpp
  MPI/MPISemantics.cpp
  MPI/MPIProcessModel.cpp
  MPI/MPIProtocolAutomaton.cpp
  MPI/MPICollectiveAnalysis.cpp
  MPI/MPIRMAAnalysis.cpp
  MPI/MPIRankAnalysis.cpp
  LinuxKernel/LinuxKernelAnalysis.cpp
  LinuxKernel/LinuxKernelProcessModel.cpp
  LinuxKernel/LinuxKernelLockAnalysis.cpp
  LinuxKernel/LinuxKernelRCUAnalysis.cpp
  LinuxKernel/LinuxKernelWaitAnalysis.cpp
)
add_library(Concurrency STATIC ${Concurrency_SOURCES})
target_link_libraries(Concurrency CanaryLLVMUtils CanaryAliasAnalysisWrapper)
