# Checker Unit Tests

add_lotus_checker_test(pulse_checker_test Pulse/PulseCheckerTest.cpp)
target_link_libraries(pulse_checker_test PulseChecker)
add_lotus_checker_test(pulse_formula_test Pulse/PulseFormulaTest.cpp)
target_link_libraries(pulse_formula_test PulseChecker)
set_target_properties(pulse_formula_test PROPERTIES CXX_STANDARD 17)
add_lotus_checker_test(concurrency_checker_test Concurrency/ConcurrencyCheckerTest.cpp)
target_link_libraries(concurrency_checker_test ConcurrencyChecker)
add_lotus_checker_test(ae_checker_test AE/AECheckerTest.cpp)
add_lotus_checker_test(kint_checker_test KINT/KINTCheckerTest.cpp)
target_link_libraries(kint_checker_test CanaryKint)
add_lotus_checker_test(saber_condition_allocator_test Saber/SaberConditionAllocatorTest.cpp)
target_link_libraries(saber_condition_allocator_test Saber)
target_compile_definitions(saber_condition_allocator_test PRIVATE USE_Z3)
