include(${CMAKE_CURRENT_LIST_DIR}/UnitTestHelpers.cmake)

add_subdirectory(Analysis)
add_subdirectory(Checker)
add_subdirectory(Concurrency)
add_subdirectory(ControlFlow)
add_subdirectory(DataFlow)
add_subdirectory(Fuzzing)
add_subdirectory(IR)
add_subdirectory(Pointer)
add_subdirectory(Solvers)
add_subdirectory(TypeHierarchy)
add_subdirectory(Utils)
add_subdirectory(Verification)
