add_subdirectory(EGraph)
add_subdirectory(Datalog)

set(LOTUS_SOLVER_SMT_TEST_SOURCES SymAbsTest.cpp SMTSamplerTest.cpp)
set(LOTUS_SOLVER_SMT_TEST_LIBS SMTSampler SymAbs ${Z3_LIBRARIES})
set(LOTUS_SOLVER_SMT_TEST_DEFINITIONS)

if(LOTUS_ENABLE_SMT_STABILIZER)
  list(APPEND LOTUS_SOLVER_SMT_TEST_SOURCES SMTStabilizerTest.cpp)
  list(APPEND LOTUS_SOLVER_SMT_TEST_LIBS LotusSMTStabilizer)
  list(APPEND LOTUS_SOLVER_SMT_TEST_DEFINITIONS
      "SMT_STABILIZER_TEST_INPUT_DIR=\"${CMAKE_CURRENT_SOURCE_DIR}/SMTStabilizerInputs\"")
endif()

add_lotus_test_suite(solver_smt_tests
  SOURCES ${LOTUS_SOLVER_SMT_TEST_SOURCES}
  LINK_LIBS ${LOTUS_SOLVER_SMT_TEST_LIBS}
  COMPILE_DEFINITIONS ${LOTUS_SOLVER_SMT_TEST_DEFINITIONS})

add_custom_target(solver_tests DEPENDS solver_egraph_tests solver_smt_tests)
